### ISSUE TITLE
[frontend] GET articles APIの取得内容をトップページに表示する

### ISSUE THREAD

**Issue by sodefrin** [arisaito/damiblog#30]
- frontendにaxiosのインストール
- apiのCORSを有効化する
- apiのindex.vueの中でaxiosを呼び出してlocalhost:3000/articlesの内容を取得する
- 取得した内容をviewに反映する

**Comment by arisaito** [comment]
@sodefrin 
axiosはインストールできたけど
apiのCORSを有効化するがわからん・・・
サーバーの用語わからなすぎて検索してもわからない・・・
https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/how-to-cors.html

**Comment by sodefrin** [comment]
何かを実現したいときには、やりたいこと+使っている言語+フレームワークで検索しましょう。

今回の場合は、まずCORSとは何なのかをググる。（難しいので理解できなくてもOK。ちょっと流し読みしてわからん！次進もうでいいです）

次にjavascript express CORSでググる。具体的な実践方法が出てくると思うのでそれも参考にしつつ先に進みましょう。

**Comment by sodefrin** [comment]
あーと思ったけど単なるGETなので必要なかったです・・・。
