### ISSUE TITLE
[frontend] トップページのデザイン

### ISSUE THREAD

**Issue by sodefrin** [arisaito/damiblog#7]
トップページのデザインを行う。まずはpages/index.vueにまとめてデザインを作成する。

html + scssで実装する。

**Comment by arisaito** [comment]
@sodefrin 
vueはvue Devoolをインストールした方がいい？
参考： https://jp.vuejs.org/v2/guide/installation.html

**Comment by arisaito** [comment]
取り急ぎ<script>で読んどく

**Comment by arisaito** [comment]
あの・・・
vue書き方がわからん｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡

**Comment by sodefrin** [comment]
nuxtで読み込めるのでnuxt Sassでググれば入れ方はでる

**Comment by sodefrin** [comment]
vueの書き方はとりあえず動かなくてもこんな感じって上げてくれればレビューします。

**Comment by sodefrin** [comment]
順番的にはこっちが先

https://github.com/arisaito/damiblog/issues/6

**Comment by arisaito** [comment]
vueって
いきなりindex.vue書くの？
色々調べてるとindex.html書いてその中でvueをCDNで呼んでる場合もあるけど
何が違うの・・・？

**Comment by sodefrin** [comment]
どっちでもできるけど、nuxtの場合はhtmlとかは自動生成されるから気にしなくていい。

https://github.com/arisaito/damiblog/blob/master/frontend/pages/index.vue

**Comment by sodefrin** [comment]
このindex.vueのhtmlの部分とcssの部分適当にいじればいいから
