### ISSUE TITLE
[frontend] 記事ページのデザイン

### ISSUE THREAD

**Issue by sodefrin** [arisaito/damiblog#8]
トップページのデザインと同様。

**Comment by arisaito** [comment]
余談

昨日、htmlでは極力id使わずclass指定って話になったけど
よくよく考えるとclassにするとめんどいな・・と思って。
というのも
JSで
let sample = document.getElementByClass("sample")
とかでclassをDOMで呼んでくると
勝手に配列扱いになってしまうので扱いがめんどくさい気がした・・・・

それは配列扱いを覚えるしかないのかな・・・・

**Comment by sodefrin** [comment]
その際にはclassとは別にIDもhtmlに記述してください。
